Command:
  aliases: [reward, storagebox, 보관함, 리워드]

Menu:
  StorageBox:
    title: '보관함'
    rows: 6
    Pattern:
      - '_________'
      - '_________'
      - '_________'
      - '_________'
      - '_________'
      - 'LAAAAAAAR'
    Items:
      A:
        type: 'orange_stained_glass_pane'
        name: ''
    Buttons:
      Left:
        Can:
          type: 'player_head'
          name: '&6왼쪽으로 넘기기'
          head-texture: 'f7aacad193e2226971ed95302dba433438be4644fbab5ebf818054061667fbe2'
        Cant:
          type: 'orange_stained_glass_pane'
          name: ''
      Right:
        Can:
          type: 'player_head'
          name: '&6오른쪽으로 넘기기'
          head-texture: 'd34ef0638537222b20f480694dadc0f85fbe0759d581aa7fcdf2e43139377158'
        Cant:
          type: 'orange_stained_glass_pane'
          name: ''

Message:
  Menu:
    out_of_space: '&9[ &fRewardAPI &9] &c공간이 부족합니다.'
  left_overs: '&9[ &fRewardAPI &9] &c보관함에 %d개의 물품이 남아있습니다.' #%d는 남은 개수를 표시합니다

Database:
  save-interval: 300
  # Json or Mysql
  type: Json
  Json:
    datafolder: './plugins/RewardAPI/data'
  MySQL:
    host: localhost
    port: 3306
    database: minecraft
    tablename: rewardapi_rewards
    parameters: '?characterEncoding=utf8'
    username: root
    password: password